name: CD Pipeline

on:
  push:
    branches:
      - release
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    # Run only if:
    # - push to release branch
    # - OR tag created whose commit belongs to release branch
    if: |
      startsWith(github.ref, 'refs/heads/release') ||
      startsWith(github.ref, 'refs/tags/')

    outputs:
      environment: ${{ steps.detect.outputs.environment }}
      image-path: ${{ steps.build-image.outputs.image-path }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed to detect branches containing tags

      - name: Determine trigger type and generate image tag
        id: detect
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/release ]]; then
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "environment=stage" >> $GITHUB_OUTPUT
          else
            # Check if tag commit is on release branch
            if git branch --contains "${GITHUB_SHA}" | grep -q "release"; then
              echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "environment=prod" >> $GITHUB_OUTPUT
            else
              echo "Tag is not from release branch. Skipping."
              echo "skip=true" >> $GITHUB_OUTPUT
            fi
          fi

      - uses: ./.github/actions/build-image
        if: steps.detect.outputs.skip != 'true'
        id: build-image
        with:
          image-tag: ${{ env.IMAGE_TAG }}
        env:
          DOCKER_REPO: ${{ vars.DOCKER_REPO }}

      - uses: ./.github/actions/run-tests
        if: steps.detect.outputs.skip != 'true'
        with:
          image-path: ${{ steps.build-image.outputs.image-path }}
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SHEET_ID: ${{ vars.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ vars.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      - uses: docker/login-action@v3
        if: steps.detect.outputs.skip != 'true'
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        if: steps.detect.outputs.skip != 'true'
        run: docker push ${{ steps.build-image.outputs.image-path }}

  continuous-deployment:
    needs: continuous-delivery
    runs-on: ubuntu-latest
    environment: ${{ needs.continuous-delivery.outputs.environment }}
    name: continuous-deployment (${{ needs.continuous-delivery.outputs.environment }})

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify auth
        run: gcloud auth list

      - name: Deploy app
        run: |
          gcloud run deploy direct-admission${{ vars.suffix }} \
            --image ${{ needs.continuous-delivery.outputs.image-path }} \
            --platform managed \
            --region ${{ vars.REGION }} \
            --allow-unauthenticated \
            --memory ${{ vars.MEMORY }} \
            --update-secrets GEMINI_API_KEY=GEMINI_API_KEY:latest \
            --set-env-vars GOOGLE_SHEET_ID="${{ vars.GOOGLE_SHEET_ID }}" \
            --set-env-vars GOOGLE_SERVICE_ACCOUNT_EMAIL="${{ vars.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" \
            --update-secrets GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest
